<paste log output from Kubernetes-mediated prediction, here>

# Pod running:

(.devops) sfcabdriver (master *) project-ml-microservice-kubernetes $ ./run_kubernetes.sh 
Error from server (AlreadyExists): pods "udacity-cloud-devops" already exists
NAME                   READY   STATUS    RESTARTS   AGE
udacity-cloud-devops   1/1     Running   0          2m9s
Forwarding from 127.0.0.1:8080 -> 80
Forwarding from [::1]:8080 -> 80
Handling connection for 8080

# After CTRL+C, pulled last 20 lines of the logs for the pod:

^C(.devops) sfcabdriver (master *) project-ml-microservice-kubernetes $ kubectl logs --tail=20 udacity-cloud-devops
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 237-958-344
[2021-02-11 02:16:42,536] INFO in app: JSON payload: 
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2021-02-11 02:16:42,570] INFO in app: Inference payload DataFrame: 
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2021-02-11 02:16:42,584] INFO in app: Scaling Payload: 
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2021-02-11 02:16:42,588] INFO in app: Prediction for Boston housing: [20.35373177134412]
127.0.0.1 - - [11/Feb/2021 02:16:42] "POST /predict HTTP/1.1" 200 -


# Output from another terminal, after running prediction script:

sfcabdriver (master *) project-ml-microservice-kubernetes $ ./make_prediction.sh 
Port: 8080
{
  "prediction": [
    20.35373177134412
  ]
}